### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [erinlloyd/Erin-Lloyd-Tea-Cozy-#5]
Grade: Exceeds Expectations

Summary: 
Erin, congrats on completing the Tea Cozy project! I loved your font choice it made the page look a bit more elegant. In the future, if you ever want to use various other fonts take a look at using [Google fonts](https://developers.google.com/fonts/docs/getting_started) it makes it very easy to import custom fonts and use them throughout your site. Overall you did a great job choosing class and id names this made it very easy to determine which sections they all pertained to. 

As a recommendation for future projects pay close attention to your HTML structure and the indentation for various levels Both are critical for making your code easy to read which is vital as your projects increase in size. Also when applying CSS to your pages analyze where you might be able to reduce duplicate styles by using classes or ids. This will help you reduce the amount of CSS you have to type which is always a plus!

As a challenge try making your [background](https://developer.mozilla.org/en-US/docs/Web/CSS/background-attachment) images fixed, some websites incorporate this technique to add some visual flair to their site.

**Comment by erinlloyd** [comment]
Thank you for the feedback and the review! Very helpful!!!
